#!/usr/bin/env python3
"""Build configs/calendar/bse_fo_holidays.toml (BSE equity-derivatives calendar) from the NSE F&O book.

Evidence, per year:
* 2021-2023: every NSE-book entry for these years already cites the BSE trading-holiday notice of that year
  (20201210-7, the 2022 BSE list, 20221208-31; see configs/calendar/README.md); kept as is.
* 2024-2026: the Upstox public market-holidays responses stored in lake/raw/upstox_holidays/ carry per-exchange
  status. For every listed date this script REQUIRES that BFO (BSE F&O) has the same closed/open status and the
  same session times as NFO (NSE F&O); any difference aborts (nothing is assumed).
Run: .venv/bin/python scripts/build_bse_calendar.py   (no network)
"""

from __future__ import annotations

import json
import sys
import tomllib
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]
NSE = REPO / "configs" / "calendar" / "nse_fo_holidays.toml"
OUT = REPO / "configs" / "calendar" / "bse_fo_holidays.toml"
RAW = REPO / "lake" / "raw" / "upstox_holidays"


def _upstox() -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    for line in (RAW / "per_date_2024_2025.jsonl").read_text().splitlines():
        r = json.loads(line)
        for e in r["response"]["data"]:
            out[e["date"]] = e
    for e in json.loads((RAW / "list_current_year_20260930T181055Z.json").read_text())["data"]:
        out[e["date"]] = e
    return out


def _status(e: dict[str, Any], exch: str) -> tuple[bool, tuple[int, int] | None]:
    closed = exch in e["closed_exchanges"]
    times = next(((o["start_time"], o["end_time"]) for o in e["open_exchanges"] if o["exchange"] == exch), None)
    return closed, times


def _q(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def main() -> int:
    book = tomllib.loads(NSE.read_text())
    ups = _upstox()
    bad = [d for d, e in ups.items() if _status(e, "NFO") != _status(e, "BFO")]
    if bad:
        print(f"BFO and NFO differ on {bad}: refusing to derive the BSE calendar")
        return 1
    lines = [
        "# BSE equity-derivatives (BFO) trading calendar, GENERATED by scripts/build_bse_calendar.py from",
        "# configs/calendar/nse_fo_holidays.toml (do not edit by hand). Same schema and loader as the NSE book.",
        "# 2021-2023: the NSE-book sources already include the BSE trading-holiday notice of each year.",
        "# 2024-2026: Upstox public market-holidays responses (lake/raw/upstox_holidays/, gitignored) show BFO",
        f"# with the same status and session times as NFO on all {len(ups)} listed dates; aborts on any difference.",
        "# Muhurat / special-session times come from the same responses (BFO times == NFO times).",
        "",
        f'version = "BSE-{book["version"]}"',
        f"covered_years = {book['covered_years']}",
        f"fixed_date_holidays = {book['fixed_date_holidays']}",
    ]
    for d in book["day"]:
        ds = d["date"].isoformat()
        srcs = list(d.get("sources", []))
        if ds >= "2024-01-01":
            if ds not in ups:
                print(f"{ds}: not in the Upstox responses; cannot confirm BFO")
                return 1
            closed, times = _status(ups[ds], "BFO")
            state = "closed" if closed else "open"
            extra = "" if times is None else " with session times"
            srcs.append(f"upstox-api market holidays: BFO {state}{extra} on {ds}, identical to NFO")
        lines += ["", "[[day]]", f"date = {ds}"]
        for k, v in d.items():
            if k in ("date", "sources"):
                continue
            if isinstance(v, bool):
                lines.append(f"{k} = {'true' if v else 'false'}")
            elif isinstance(v, str):
                lines.append(f"{k} = {_q(v)}")
            else:
                lines.append(f"{k} = {v if not hasattr(v, 'isoformat') else v.isoformat()}")
        lines.append(f"sources = [{', '.join(_q(s) for s in srcs)}]")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(REPO)} ({len(book['day'])} days)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
