"""Project 100C - feasibility arithmetic (design-phase analysis, NOT trading code).

Reproduces the numbers quoted in README.md / 01-architecture.md.
All premiums are Black-Scholes ESTIMATES from a spot/IV assumption, not market quotes.
Run: python3 tools/feasibility_calc.py
"""

import math

# ---- Inputs (verified 30-Sep-2026 unless marked) ----
LOT = 65  # NIFTY lot size (NSE circular FAOP70616, eff. Jan-2026 expiries)
SPOT = 22716.20  # NIFTY close reported for 29-Sep-2026 session (news sources; approx)
IV = 0.1332  # India VIX close 29-Sep-2026 used as ATM IV proxy (ASSUMPTION)
R = 0.055  # risk-free proxy (ASSUMPTION; immaterial at these tenors)
NAV = 10_000
MAX_LOSS_PCT = 0.02

# Statutory / exchange charges (verified, see docs/engineering/sources.md)
STT_SELL = 0.0015  # 0.15% of premium, sell side (Finance Act 2026, w.e.f. 1-Apr-2026)
NSE_TXN = 0.0003553  # Rs 3,553 / crore of premium incl. IPFT (NSE, w.e.f. 1-Mar-2026)
SEBI_FEE = 10 / 1e7  # Rs 10 / crore
STAMP_BUY = 0.00003  # 0.003% buy side
GST = 0.18  # on brokerage + txn + SEBI fee


def ncdf(x):
    return 0.5 * (1 + math.erf(x / math.sqrt(2)))


def bs_call(S, K, T, sigma, r=R):
    if T <= 0:
        return max(S - K, 0.0)
    d1 = (math.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * math.sqrt(T))
    d2 = d1 - sigma * math.sqrt(T)
    return S * ncdf(d1) - K * math.exp(-r * T) * ncdf(d2)


def bs_delta(S, K, T, sigma, r=R):
    d1 = (math.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * math.sqrt(T))
    return ncdf(d1)


def round_trip_charges(p_buy, p_sell, brokerage_per_order):
    b = p_buy * LOT
    s = p_sell * LOT
    brokerage = 2 * brokerage_per_order
    stt = STT_SELL * s
    txn = NSE_TXN * (b + s)
    sebi = SEBI_FEE * (b + s)
    stamp = STAMP_BUY * b
    gst = GST * (brokerage + txn + sebi)
    total = brokerage + stt + txn + sebi + stamp + gst
    return dict(brokerage=brokerage, stt=stt, txn=txn, sebi=sebi, stamp=stamp, gst=gst, total=total)


def main():
    atm = round(SPOT / 50) * 50
    print("# Feasibility output (generated by feasibility_calc.py)\n")
    print(
        f"Inputs: spot={SPOT}, ATM strike={atm}, IV={IV:.2%} (VIX proxy, ASSUMPTION), lot={LOT}, NAV=Rs{NAV:,}, "
        f"max loss/trade = {MAX_LOSS_PCT:.0%} = Rs{NAV * MAX_LOSS_PCT:.0f}\n"
    )
    print(f"Notional of one lot = {LOT} x {SPOT:,.0f} = Rs{LOT * SPOT:,.0f}\n")
    budget = NAV * MAX_LOSS_PCT
    stop_pts = budget / LOT
    print(
        f"Max stop width for Rs{budget:.0f} risk on one lot = {budget:.0f}/{LOT} = **{stop_pts:.2f} premium points** "
        "(before costs and slippage)\n"
    )

    print("## A. Estimated call premiums (Black-Scholes, flat IV; real smiles/skew differ)\n")
    print(
        "| Calendar days to expiry | Strike (moneyness) | Est. premium (pts) | Delta | One-lot cost (Rs) | % of Rs10k NAV | Rs200 stop as % of premium |"
    )
    print("|---|---|---|---|---|---|---|")
    for dte in [0.25, 1, 3, 6]:
        T = dte / 365
        for off in [0, 100, 200, 300, 500]:
            K = atm + off
            p = bs_call(SPOT, K, T, IV)
            if p < 0.05:
                continue
            d = bs_delta(SPOT, K, T, IV)
            cost = p * LOT
            print(
                f"| {dte} | {K} (ATM+{off}) | {p:.1f} | {d:.2f} | {cost:,.0f} | {cost / NAV:.0%} | "
                f"{(stop_pts / p) if p > 0 else float('nan'):.0%} |"
            )
    print()

    print("## B. Round-trip charges for ONE lot (buy + sell at same premium), statutory rates as of 30-Sep-2026\n")
    print(
        "| Premium (pts) | Brokerage/order | Brokerage | STT | NSE txn | SEBI | Stamp | GST | **Total Rs** | % of NAV | % of Rs200 risk budget |"
    )
    print("|---|---|---|---|---|---|---|---|---|---|---|")
    for p in [10, 30, 60, 100, 150]:
        for brk in [20, 0]:
            c = round_trip_charges(p, p, brk)
            print(
                f"| {p} | Rs{brk} | {c['brokerage']:.2f} | {c['stt']:.2f} | {c['txn']:.2f} | {c['sebi']:.3f} | "
                f"{c['stamp']:.2f} | {c['gst']:.2f} | **{c['total']:.2f}** | {c['total'] / NAV:.2%} | {c['total'] / budget:.0%} |"
            )
    print()

    print(
        "## C. Slippage scenarios (ASSUMED, to be measured live): cost of crossing/adverse fill per round trip, one lot\n"
    )
    print("| Slippage per side (pts) | Round-trip slippage (Rs) | % of Rs200 budget |")
    print("|---|---|---|")
    for sl in [0.05, 0.25, 0.5, 1.0, 2.0]:
        rs = 2 * sl * LOT
        print(f"| {sl} | {rs:.1f} | {rs / budget:.0%} |")
    print()

    print("## D. Minimum NAV that makes the directive's 2% rule workable (one lot)\n")
    print(
        "Criteria (design assumptions): stop >= 25% of premium (outside noise), round-trip friction "
        "(charges at Rs20/order + 0.5pt/side slippage) <= 25% of the per-trade risk budget, and premium outlay <= 25% of NAV.\n"
    )
    print(
        "| Premium (pts) | Stop @25% (pts) | Loss at stop incl. friction (Rs) | NAV needed by 2% rule | NAV by friction<=25% budget | NAV by outlay<=25% NAV | **Binding min NAV** |"
    )
    print("|---|---|---|---|---|---|---|")
    for p in [10, 20, 30, 60, 100, 150]:
        stop = 0.25 * p
        fr = round_trip_charges(p, p - stop, 20)["total"] + 2 * 0.5 * LOT
        loss = stop * LOT + fr
        nav_rule = loss / MAX_LOSS_PCT
        nav_fric = fr / (0.25 * MAX_LOSS_PCT)
        nav_out = p * LOT / 0.25
        need = max(nav_rule, nav_fric, nav_out)
        print(
            f"| {p} | {stop:.1f} | {loss:,.0f} | {nav_rule:,.0f} | {nav_fric:,.0f} | {nav_out:,.0f} | **{need:,.0f}** |"
        )
    print()


if __name__ == "__main__":
    main()
